site_name: Immudb documentation
site_url: https://immudb-testowa-dokumentacja.readthedocs.io/en/latest/

nav:
    - 'index.md'
    - 'about.md'
    - 'concepts.md'
    - 'releasenotes.md'
    - 'getstarted/build.md'
    - 'getstarted/clitools.md'
    - 'getstarted/jumpstart.md'
    - 'getstarted/quickstart.md'
    - 'getstarted/webconsole.md'

