site_name: Immudb documentation
site_url: https://github.com/codenotary/immudb
nav:
    - Home: index.md
    - About Immudb: about.md
    - Concepts: concepts.md
    - Release notes: releasenotes.md
    - Build: getstarted/build.md
    - CLI Tools: getstarted/clitools.md
    - Jumpstart: getstarted/jumpstart.md
    - Quick Start: getstarted/quickstart.md
    - Web console: getstarted/webconsole.md

theme: readthedocs